repos:
  -   repo: local
      hooks:
        - id: create-code-check-directory
          name: Create code check directory
          entry: mkdir -p code_check
          language: system
          pass_filenames: false
          always_run: true

  -   repo: local
      hooks:
        - id: clang-format-dry-run
          name: Run clang-format-dry
          entry: clang-format --dry-run --style=file --verbose
          verbose: true
          language: system
          files: \.(cpp|cc|c|h|hpp)$

  -   repo: local
      hooks:
        -   id: clang-format
            name: Run clang-format
            entry: clang-format -i
            language: system
            verbose: true
            files: \.(cpp|cc|c|h|hpp)$
            args: [--style=file]

  -   repo: local
      hooks:
          - id: cppcheck
            name: Run Cppcheck
            entry: cppcheck
            args: [
              "--enable=performance",
              "--language=c++",
              "--std=c++17",
              "--suppressions-list=.cppcheck_exclude",
              "--error-exitcode=1",
              "-j4",
              "-v",
              "-q",
              "--output-file=code_check/pre_commit_cppcheck.log"
            ]
            language: system
            files: \.(cpp|cc|c|h|hpp)$
            verbose: true
            description: Run Cppcheck static analysis tool and show detailed output.

  - repo: git@10.10.42.100:pnc/third_party/gitlint.git
    rev: v0.19.1
    hooks:
      - id: gitlint