sonar.projectKey=navigation
sonar.sources=.
sonar.test.inclusions=**/test/*
sonar.exclusions=pnc_common_package/modules/ninebot_log/*,**/test/*
sonar.python.version=3
sonar.cxx.file.suffixes=.cc,.cpp,.cxx,.c++,.hh,.hpp,.hxx,.h++,.ipp
sonar.cxx.cppcheck.reportPaths=code_check/cppcheck_result.xml
sonar.cxx.clangtidy.reportPaths=code_check/clang-tidy_result.log
sonar.cxx.cobertura.reportPaths=code_check/coverage_output.xml